1. 다음 행렬 연산을 파이썬 넘파이 프로그램을 이용해서 계산하세요.

$$A = \begin{bmatrix}
       1 & 2 & 3 \\
       4 & 5 & 6 \\
      \end{bmatrix},
B = \begin{bmatrix}
       1 & 0 \\
       0 & 1 \\
       1 & 1 \\
       \end{bmatrix}$$

a. $2A$

b. $A$의 각 성분의 제곱
$$\begin{bmatrix}
       1^2 & 2^2 &3^2 \\
       4^2 & 5^2 &6^2 \\
       \end{bmatrix}$$
c. 두 행렬의 곱 $AB$

In [14]:
import numpy as np
A = np.array([1,2,3,4,5,6]).reshape((2,3))
B = np.array([1,0,0,1,1,1]).reshape((3,2))

# a.
print(2*A)

# b.
print(A**2)

# c.
print(A.dot(B))

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[ 4  5]
 [10 11]]


2. 넘파이 ```reshape``` 함수를 이용하여 다음과 같은 행렬을 만드세요.
    ```python
    1 2 3 4
    5 6 7 8
    9 10 11 12
    ```

In [16]:
import numpy as np

matrix = np.arange(1,13).reshape((3,4))
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. 넘파이 `zeros, ones, eye` 함수를 이용해 `3x5` 영행렬, 성분이 모두 `1`로만 이루어진 `2x3` 행렬, `5x5` 단위행렬을 각각 만드세요.

In [2]:
import numpy as np

zero_matrix = np.zeros(shape=(3,5))
print(zero_matrix)
ones_matrix = np.ones(shape=(2,3))
print(ones_matrix)
eye_matrix = np.eye(5)
print(eye_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


4. 넘파이 `3x1x2` 와 `2x2` 배열을 더할 때 브로드캐스트 되는 과정을 다음 배열 A, B를 이용해서 자세히 설명하세요.
    ```python
    A = np.arange(6).reshape(3, 1, 2)
    B = np.arange(6, 10).reshape(2, 2)
    print('A=', A, '\nB=', B)

    A= [[[0 1]]
        [[2 3]]
        [[4 5]]] 
    B= [[6 7]
        [8 9]]
    ```

* 두 배열의 크기를 끝부터 맞추고, 축이 없는 부분은 1로 채운다.\
A : 3 x 1 x 2 \
B : 1 x 2 x 2

* 뒤에서부터 크기가 1인 부분을 다른 배열의 같은 축의 크기에 맞춰 복사하여 브로드캐스트를 한다.\
A : 3 x 2 x 2 \
B : 3 x 2 x 2 

* 따라서 `3x1x2` 였던 A 배열은 `3x2x2`가 되고 `2x2`였던 B 배열은 `3x2x2`가 된다.
```python
A = [[[0 1]
      [0 1]]
     [[2 3]
      [2 3]]
     [[4 5]
      [4 5]]]
B = [[[6 7]
      [8 9]]
     [[6 7]
      [8 9]]
     [[6 7]
      [8 9]]]
```
* A와 B의 덧셈은 아래와 같은 결과가 나온다.
```python
A+B = [[[6 8]
        [8 10]]
       [[8 10]
        [10 12]]
       [[10 12]
        [12 14]]]
```

In [4]:
import numpy as np
A = np.arange(6).reshape(3, 1, 2)
B = np.arange(6, 10).reshape(2, 2)
print('A=', A, 'nB=', B) 

print('\nA+B=',A+B)

A= [[[0 1]]

 [[2 3]]

 [[4 5]]] nB= [[6 7]
 [8 9]]

A+B= [[[ 6  8]
  [ 8 10]]

 [[ 8 10]
  [10 12]]

 [[10 12]
  [12 14]]]


5. 다음 행렬 `A`의 원소가 `0`보다 작은 값을 모두 `0`으로 대체하세요.
$$A=\begin{bmatrix}
       -1 & 2 & -5.4 \\
       0 & 1 & -100.5 \\
      \end{bmatrix}$$
 

In [9]:
import numpy as np

A = np.array([-1,2,-5.4,0,1,-100.5]).reshape((2,3))
A_shape = A.shape

for i in range(A_shape[0]):
    for j in range(A_shape[1]):
        if A[i][j]<0:
            A[i][j]=0
print(A)

[[0. 2. 0.]
 [0. 1. 0.]]


6. 직사각형 클래스 `Rectangle`을 작성하는데, `area()`, `diagonal()` 메소드를 갖도록 하세요. `area`는 직사각형의 면적을 출력하고 `diagonal`은 직사각형의 대각선의 길이를 출력하는 프로그램을 작성하세요. 직사각형을 초기화할 때, 너비와 높이를 입력하도록 `__init__(self, width, height)` 메소드를 작성하세요.

In [11]:
import math
class Rectangle:
    def __init__(self, width, height) -> None:
        self.width = width
        self.height = height
    def area(self):
        area = self.width * self.height
        print(area)
    def diagonal(self):
        diagonal = math.sqrt(self.width**2+self.height**2)
        print(diagonal)

rectangle = Rectangle(4,7)
width = rectangle.area()   
diagonal = rectangle.diagonal()     
        

28
8.06225774829855


7. Dog 클래스를 작성하는데 메소드는 `eat()`, `walk()`, `info()`를 갖도록 하세요. `eat` 메소드는 음식을 인자로 받아들여서 먹은 음식을 출력하고, `walk` 메소드를 실행할 때 마다 2미터씩 움직이도록 합니다. `info()`를 실행하면 이름이 뭐고, 무엇을 먹었고 얼마나 움직였는지를 출력하도록 프로그래밍을 하세요. 초기화할 때 강아지 이름을 입력할 수 있도록 `__init__(self, name)` 메소드를 작성하도록 하세요.

In [24]:
class Dog:
    def __init__(self,name) -> None:
        self.name = name
        self.distance = 0
    def eat(self,food):
        self.food = food
        print(self.name+"이가 먹은 음식은 " + self.food +"입니다.")
    def walk(self):
        self.distance += 2
        print(self.distance)
    def info(self):
        print(f"이름은 {self.name}이고, 먹은 음식은 {self.food}, {self.distance}미터를 움직였습니다.")

dog = Dog("밥풀")
food = dog.eat("개껌")
distance = dog.walk()
distance = dog.walk()
information = dog.info()
        

밥풀이가 먹은 음식은 개껌입니다.
2
4
이름은 밥풀이고, 먹은 음식은 개껌, 4미터를 움직였습니다.
